/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconCapture',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M3 9a1 1 0 001-1V5a1 1 0 011-1h3a1 1 0 000-2H5a3 3 0 00-3 3v3a1 1 0 001 1Zm5 11H5a1 1 0 01-1-1v-3a1 1 0 00-2 0v3a3 3 0 003 3h3a1 1 0 000-2Zm4-12a4 4 0 104 4 4 4 0 00-4-4Zm0 6a2 2 0 112-2 2 2 0 01-2 2Zm7-12h-3a1 1 0 000 2h3a1 1 0 011 1v3a1 1 0 002 0V5a3 3 0 00-3-3Zm2 13a1 1 0 00-1 1v3a1 1 0 01-1 1h-3a1 1 0 000 2h3a3 3 0 003-3v-3a1 1 0 00-1-1Z"/>
      </svg>
    )
  }
})
