// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconAlignBottom',
  render() {
    return (
      <svg viewBox="0 0 256 256" width="1em" height="1em">
        <path fill="currentColor" d="M224 216a8 8 0 01-8 8H40a8 8 0 010-16h176a8 8 0 018 8Zm-88-40V80a16 16 0 0116-16h40a16 16 0 0116 16v96a16 16 0 01-16 16h-40a16 16 0 01-16-16Zm16 0h40V80h-40Zm-104 0V40a16 16 0 0116-16h40a16 16 0 0116 16v136a16 16 0 01-16 16H64a16 16 0 01-16-16Zm16 0h40V40H64Z"/>
      </svg>
    )
  }
})
