/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconRoundPlus',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M18 12.998h-5v5a1 1 0 01-2 0v-5H6a1 1 0 010-2h5v-5a1 1 0 012 0v5h5a1 1 0 010 2z"/>
      </svg>
    )
  }
})
