/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconMarkdownLine',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M3 3h18a1 1 0 011 1v16a1 1 0 01-1 1H3a1 1 0 01-1-1V4a1 1 0 011-1Zm1 2v14h16V5H4Zm3 10.5H5v-7h2l2 2 2-2h2v7h-2v-4l-2 2-2-2v4Zm11-3h2l-3 3-3-3h2v-4h2v4Z"/>
      </svg>
    )
  }
})
