/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconAlarm',
  render() {
    return (
      <svg viewBox="0 0 256 256" width="1em" height="1em">
        <path fill="currentColor" d="M128 32a96 96 0 1096 96 96.11 96.11 0 00-96-96Zm0 176a80 80 0 1180-80 80.09 80.09 0 01-80 80ZM61.66 29.66l-32 32a8 8 0 01-11.32-11.32l32-32a8 8 0 1111.32 11.32Zm176 32a8 8 0 01-11.32 0l-32-32a8 8 0 0111.32-11.32l32 32a8 8 0 010 11.32ZM184 120a8 8 0 010 16h-56a8 8 0 01-8-8V72a8 8 0 0116 0v48Z"/>
      </svg>
    )
  }
})
