/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconCaretDoubleRightBold',
  render() {
    return (
      <svg viewBox="0 0 256 256" width="1em" height="1em">
        <path fill="currentColor" d="m144.49 136.49-80 80a12 12 0 01-17-17L119 128 47.51 56.49a12 12 0 0117-17l80 80a12 12 0 01-.02 17Zm80-17-80-80a12 12 0 10-17 17L199 128l-71.52 71.51a12 12 0 0017 17l80-80a12 12 0 00.01-17Z"/>
      </svg>
    )
  }
})
