// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconAtSign',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"><circle cx="12" cy="12" r="4"/><path d="M16 8v5a3 3 0 006 0v-1a10 10 0 10-3.92 7.94"/></g>
      </svg>
    )
  }
})
