// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconFormatHorizontalAlignLeft',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M11 16v-3h10v-2H11V8l-4 4 4 4m-8 4h2V4H3v16Z"/>
      </svg>
    )
  }
})
