/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconMoonWaningCrescent',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M2 12a10 10 0 0013 9.54 10 10 0 010-19.08A10 10 0 002 12Z"/>
      </svg>
    )
  }
})
