// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconCloudServiceManagement',
  render() {
    return (
      <svg viewBox="0 0 32 32" width="1em" height="1em">
        <path fill="currentColor" d="M28 17v5H4V6h10V4H4a2 2 0 00-2 2v16a2 2 0 002 2h8v4H8v2h16v-2h-4v-4h8a2 2 0 002-2v-5ZM18 28h-4v-4h4Z"/><path fill="currentColor" d="M30 10V8h-2.101a4.968 4.968 0 00-.732-1.753l1.49-1.49-1.414-1.414-1.49 1.49A4.968 4.968 0 0024 4.101V2h-2v2.101a4.968 4.968 0 00-1.753.732l-1.49-1.49-1.414 1.414 1.49 1.49A4.968 4.968 0 0018.101 8H16v2h2.101a4.968 4.968 0 00.732 1.753l-1.49 1.49 1.414 1.414 1.49-1.49a4.968 4.968 0 001.753.732V16h2v-2.101a4.968 4.968 0 001.753-.732l1.49 1.49 1.414-1.414-1.49-1.49A4.968 4.968 0 0027.899 10Zm-7 2a3 3 0 113-3 3.003 3.003 0 01-3 3Z"/>
      </svg>
    )
  }
})
