/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconCaretDoubleLeftBold',
  render() {
    return (
      <svg viewBox="0 0 256 256" width="1em" height="1em">
        <path fill="currentColor" d="M208.49 199.51a12 12 0 01-17 17l-80-80a12 12 0 010-17l80-80a12 12 0 0117 17L137 128ZM57 128l71.52-71.51a12 12 0 00-17-17l-80 80a12 12 0 000 17l80 80a12 12 0 0017-17Z"/>
      </svg>
    )
  }
})
