// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconAndroidLogo',
  render() {
    return (
      <svg viewBox="0 0 256 256" width="1em" height="1em">
        <path fill="currentColor" d="M176 156a12 12 0 11-12-12 12 12 0 0112 12Zm-84-12a12 12 0 1012 12 12 12 0 00-12-12Zm148 24v24a16 16 0 01-16 16H32a16 16 0 01-16-16v-22.87a113.38 113.38 0 0135.4-82.41L26.34 61.66a8 8 0 0111.32-11.32L63.82 76.5a111.43 111.43 0 01128.55-.19l26-26a8 8 0 0111.32 11.32L204.82 86.5c.75.71 1.5 1.43 2.24 2.17A111.25 111.25 0 01240 168Zm-16 0a96 96 0 00-96-96h-.34C74.91 72.18 32 115.75 32 169.13V192h192Z"/>
      </svg>
    )
  }
})
