/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconEditor',
  render() {
    return (
      <svg viewBox="0 0 48 48" width="1em" height="1em">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="4"><path stroke-linejoin="round" d="M40 33v9a2 2 0 01-2 2h-6.5M40 16V6a2 2 0 00-2-2H10a2 2 0 00-2 2v36a2 2 0 002 2h6"/><path d="M16 16h14m-7 28 17-21m-24 1h8"/></g>
      </svg>
    )
  }
})
