/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconPrinter',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M18 3H6v4h12m1 5a1 1 0 01-1-1 1 1 0 011-1 1 1 0 011 1 1 1 0 01-1 1m-3 7H8v-5h8m3-6H5a3 3 0 00-3 3v6h4v4h12v-4h4v-6a3 3 0 00-3-3Z"/>
      </svg>
    )
  }
})
