// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconFormatHorizontalAlignRight',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M13 8v3H3v2h10v3l4-4-4-4m6 12h2V4h-2v16Z"/>
      </svg>
    )
  }
})
