// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconNotificationLine',
  render() {
    return (
      <svg viewBox="0 0 36 36" width="1em" height="1em">
        <path fill="currentColor" d="M32.51 27.83A14.4 14.4 0 0130 24.9a12.63 12.63 0 01-1.35-4.81v-4.94A10.81 10.81 0 0019.21 4.4V3.11a1.33 1.33 0 10-2.67 0v1.31a10.81 10.81 0 00-9.33 10.73v4.94a12.63 12.63 0 01-1.35 4.81 14.4 14.4 0 01-2.47 2.93 1 1 0 00-.34.75v1.36a1 1 0 001 1h27.8a1 1 0 001-1v-1.36a1 1 0 00-.34-.75ZM5.13 28.94a16.17 16.17 0 002.44-3 14.24 14.24 0 001.65-5.85v-4.94a8.74 8.74 0 1117.47 0v4.94a14.24 14.24 0 001.65 5.85 16.17 16.17 0 002.44 3Z" class="clr-i-outline clr-i-outline-path-1"/><path fill="currentColor" d="M18 34.28A2.67 2.67 0 0020.58 32h-5.26A2.67 2.67 0 0018 34.28Z" class="clr-i-outline clr-i-outline-path-2"/><path fill="none" d="M0 0h36v36H0z"/>
      </svg>
    )
  }
})
