/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconBaselineBlock',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zM4 12c0-4.42 3.58-8 8-8 1.85 0 3.55.63 4.9 1.69L5.69 16.9A7.902 7.902 0 014 12zm8 8c-1.85 0-3.55-.63-4.9-1.69L18.31 7.1A7.902 7.902 0 0120 12c0 4.42-3.58 8-8 8z"/>
      </svg>
    )
  }
})
