// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconSearch',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M21.71 20.29 18 16.61A9 9 0 1016.61 18l3.68 3.68a1 1 0 001.42 0 1 1 0 000-1.39ZM11 18a7 7 0 117-7 7 7 0 01-7 7Z"/>
      </svg>
    )
  }
})
