// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconBookInformation24Regular',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M13.25 7a1 1 0 11-2 0 1 1 0 012 0ZM11.5 9.75v5a.75.75 0 001.5 0v-5a.75.75 0 00-1.5 0ZM4 4.5A2.5 2.5 0 016.5 2H18a2.5 2.5 0 012.5 2.5v14.25a.75.75 0 01-.75.75H5.5a1 1 0 001 1h13.25a.75.75 0 010 1.5H6.5A2.5 2.5 0 014 19.5v-15ZM19 18V4.5a1 1 0 00-1-1H6.5a1 1 0 00-1 1V18H19Z"/>
      </svg>
    )
  }
})
