/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconPluginLine',
  render() {
    return (
      <svg viewBox="0 0 36 36" width="1em" height="1em">
        <path fill="currentColor" d="M29.81 16H29V8.83a2 2 0 00-2-2h-6A5.14 5.14 0 0016.51 2 5 5 0 0011 6.83H4a2 2 0 00-2 2V17h2.81A3.13 3.13 0 018 19.69 3 3 0 017.22 22 3 3 0 015 23H2v8.83a2 2 0 002 2h23a2 2 0 002-2V26h1a5 5 0 005-5.51A5.15 5.15 0 0029.81 16Zm2.41 7A3 3 0 0130 24h-3v7.83H4V25h1a5 5 0 005-5.51A5.15 5.15 0 004.81 15H4V8.83h9V7a3 3 0 011-2.22A3 3 0 0116.31 4 3.13 3.13 0 0119 7.19v1.64h8V18h2.81A3.13 3.13 0 0133 20.69a3 3 0 01-.78 2.31Z" class="clr-i-outline clr-i-outline-path-1"/><path fill="none" d="M0 0h36v36H0z"/>
      </svg>
    )
  }
})
