/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconLineOutlined',
  render() {
    return (
      <svg viewBox="0 0 1024 1024" width="1em" height="1em">
        <path fill="currentColor" d="M904 476H120c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h784c4.4 0 8-3.6 8-8v-56c0-4.4-3.6-8-8-8z"/>
      </svg>
    )
  }
})
