/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconApps',
  render() {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em">
        <path fill="currentColor" d="M16 20h4v-4h-4m0-2h4v-4h-4m-6-2h4V4h-4m6 4h4V4h-4m-6 10h4v-4h-4m-6 4h4v-4H4m0 10h4v-4H4m6 4h4v-4h-4M4 8h4V4H4v4Z"/>
      </svg>
    )
  }
})
