// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconUserAvatar',
  render() {
    return (
      <svg viewBox="0 0 32 32" width="1em" height="1em">
        <path fill="currentColor" d="M16 8a5 5 0 105 5 5 5 0 00-5-5Zm0 8a3 3 0 113-3 3.003 3.003 0 01-3 3Z"/><path fill="currentColor" d="M16 2a14 14 0 1014 14A14.016 14.016 0 0016 2Zm-6 24.377V25a3.003 3.003 0 013-3h6a3.003 3.003 0 013 3v1.377a11.899 11.899 0 01-12 0Zm13.992-1.451A5.002 5.002 0 0019 20h-6a5.002 5.002 0 00-4.992 4.926 12 12 0 1115.985 0Z"/>
      </svg>
    )
  }
})
