// Generated by vite-plugin-icon
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IconAllApplication',
  render() {
    return (
      <svg viewBox="0 0 48 48" width="1em" height="1em">
        <path fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="4" d="M18 6H8a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V8a2 2 0 00-2-2Zm0 22H8a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V30a2 2 0 00-2-2ZM40 6H30a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V8a2 2 0 00-2-2Zm0 22H30a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V30a2 2 0 00-2-2Z"/>
      </svg>
    )
  }
})
