export { default as SettingDrawer } from './setting-drawer/index.vue'
export { default as GlobalHeader } from './global-header/index.vue'
export { default as GlobalTab } from './global-tab/index.vue'
export { default as GlobalSider } from './global-sider/index.vue'
export { default as GlobalContent } from './global-content/index.vue'
export { default as GlobalFooter } from './global-footer/index.vue'
export { default as GlobalLogo } from './global-logo/index.vue'
